---
title: "Draft_code"
editor: visual
---

Denne HTML filen består kun av kladde kode og potensielle fallgruver med skjevhet i valg av metode/datapunkter.

```{r}
#| message: false
#| warning: false
library(readr)
library(dplyr)
library(sf)
library(rnaturalearth)
library(ggplot2)

load("herring_data_alt.rda")

herring_data <- herring_data |> 
  st_as_sf(coords = c("lon", "lat"), crs = 4326)

# Omdanner geometry kolonne til df med lat/lon
coord_df <- st_coordinates(herring_data) |> 
  as.data.frame() |> 
  rename(lon = X, lat = Y)

# plot
europe <- ne_countries(continent = "Europe", returnclass = "sf")
ggplot() +
  geom_sf(data = europe, fill = "antiquewhite", color = "gray60") +
  geom_bin2d(
    data = coord_df,
    aes(x = lon, y = lat),
    binwidth = c(0.5, 0.5)  # 0.5° grid (~50 km)
  ) +
  scale_fill_viridis_c(trans = "log", na.value = "white") +
  coord_sf(xlim = c(0, 37), ylim = c(55, 76)) +
  theme_minimal() +
  labs(title = "Herring data 1935 - 2019", subtitle = "Number of observations per grid cell")
```

Sjekker årene 1970 - 2019

```{r}
#| message: false
#| warning: false
library(readr)
library(dplyr)
library(sf)
library(rnaturalearth)
library(ggplot2)

load("herring_data_alt.rda")

herring_data <- herring_data |> 
  filter(year >= 1970, year <= 2019) |> 
  st_as_sf(coords = c("lon", "lat"), crs = 4326)

# Omdanner geometry kolonne til df med lat/lon
coord_df <- st_coordinates(herring_data) |> 
  as.data.frame() |> 
  rename(lon = X, lat = Y)

map_catches_binned_1970_2019 <- ggplot() +
  geom_sf(data = europe, fill = "antiquewhite", color = "gray60") +
  geom_bin2d(
    data = coord_df,
    aes(x = lon, y = lat),
    binwidth = c(0.5, 0.5)  # 0.5° grid (~50 km)
  ) +
  scale_fill_viridis_c(trans = "log", na.value = "white") +
  coord_sf(xlim = c(0, 37), ylim = c(55, 76)) +
  theme_minimal() +
  labs(title = "Herring data 1970 - 2019", subtitle = "Number of observations per grid cell")

map_catches_binned_1970_2019
```

```{r}
#| message: false
#| warning: false
library(readr)
library(dplyr)
library(sf)
library(rnaturalearth)
library(ggplot2)

load("herring_data_alt.rda")

herring_data <- herring_data |> 
  filter(year >= 2000, year <= 2019) |> 
  st_as_sf(coords = c("lon", "lat"), crs = 4326)

# Omdanner geometry kolonne til df med lat/lon
coord_df <- st_coordinates(herring_data) |> 
  as.data.frame() |> 
  rename(lon = X, lat = Y)

map_catches_binned_2000_2019 <- ggplot() +
  geom_sf(data = europe, fill = "antiquewhite", color = "gray60") +
  geom_bin2d(
    data = coord_df,
    aes(x = lon, y = lat),
    binwidth = c(0.5, 0.5)  # 0.5° grid (~50 km)
  ) +
  scale_fill_viridis_c(trans = "log", na.value = "white") +
  coord_sf(xlim = c(0, 37), ylim = c(55, 76)) +
  theme_minimal() +
  labs(title = "Herring data 2000 - 2019", subtitle = "Number of observations per grid cell")

map_catches_binned_2000_2019
```

\##########################################

Mulige problemer med skjevet i datasettet mtp. hvor sampling size

```{r}
#| message: false
#| warning: false
#install.packages("DT")
library(dplyr)
library(tidyr)
library(knitr)
library(DT)

herring_data <- readRDS("herring_data.rds")

sex_year_wide <- herring_data |>
  mutate(sex_chr = ifelse(is.na(sex), "NA", as.character(sex))) |> 
  group_by(year, sex_chr) |>
  summarise(n = n(), .groups = "drop") |>
  tidyr::pivot_wider(
    names_from = sex_chr,
    values_from = n,
    values_fill = 0
  ) |>
  mutate(Total = rowSums(across(-year)))

# interaktiv tabell
datatable(sex_year_wide)

```

Jeg må vurdere hvordan skjevheten i innsamlet datapunkter påvirker modellering

```{r}
#| message: false
#| warning: false
library(ggplot2)

ggplot(sex_year_wide, aes(x = year, y = Total)) +
  geom_line(color = "steelblue", linewidth = 1) +
  geom_point(color = "steelblue") +
  labs(
    title = "Totalt antall datapunkter per år",
    x = "År",
    y = "Totalt antall datapunkter"
  ) +
  scale_x_continuous(
    breaks = seq(min(sex_year_wide$year), max(sex_year_wide$year), by = 5)  # hvert 5. år
  ) +
  scale_y_continuous(
    breaks = scales::pretty_breaks(n = 10)  # 10 ticks på y-aksen
  ) +
  theme_minimal(base_size = 13) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
```
